FROM node:24-alpine

# make the 'app' folder the current working directory
WORKDIR /app

# copy package.json (and package-lock.json) if available
COPY package*.json ./

# install depencies
RUN npm install

EXPOSE 5173
