services:
  backend:
    container_name: express
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/pagepulse.db
      - PORT=3000
    restart: unless-stopped

  frontend:
    container_name: vue
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./app:/app