FROM node:24-alpine

RUN apk add sqlite

WORKDIR /app

COPY package*.json ./
RUN npm ci --workspaces=false

COPY . .

RUN mkdir -p /app/data && chown -R node:node /app/data

USER node

EXPOSE 3000

CMD sh -c "npx tsx ./node_modules/.bin/knex --knexfile src/db/knexfile.ts migrate:latest && npx tsx src/index.ts"