FROM node:24-alpine AS builder

# make the 'app' folder the current working directory
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npx tsc

# --- Production image ---
FROM node:24-alpine

# make the 'app' folder the current working directory
WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["node", "dist/index.js"]
